" Configuration file for vim
set modelines=0		" CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=2		" more powerful backspacing

syntax on
set smartindent
set autoindent

set tabstop=2
set softtabstop=2
set shiftwidth=2

set expandtab

set number

set hlsearch
set incsearch

set encoding=utf-8

set ruler

set showcmd

set showmatch

